### ISSUE TITLE
Learn Go

### ISSUE THREAD

**Issue by vkorbes** [ellenkorbes/ellenkorbes.github.io#14]
https://golang.org/doc/

**Comment by ellenkorbes** [comment]
https://golang.org/doc/

**Comment by vkorbes** [comment]
http://exercism.io/languages/go/about
https://tour.golang.org/welcome/1
https://gobyexample.com/

**Comment by vkorbes** [comment]
UPDATE: The official tour sucks. Now I'm going with the gobyexample.com files, making sure I can make sense of them and typing them out myself. 

(Also, read this: https://blog.golang.org/go-slices-usage-and-internals)

**Comment by vkorbes** [comment]
Kris' tweet resources:
https://www.youtube.com/watch?v=cN_DpYBzKso
https://changelog.com/gotime
https://github.com/arschles/go-in-5-minutes
https://www.reddit.com/r/golang/

**Comment by vkorbes** [comment]
http://www.golangbootcamp.com/book/frontmatter
